name: Compilation

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  job_build_debug:
    name: Build debug
    runs-on: ubuntu-latest

    container:
      image: docker://ledgerhq/ledger-app-builder:1.6.0

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Build
        run: |
          make DEBUG=1

      - name: Upload app binary
        uses: actions/upload-artifact@v2
        with:
          name: monero-app-debug
          path: bin

  job_test:
    name: Test
    needs: job_build_debug
    runs-on: ubuntu-latest

    container:
      image: docker://ledgerhq/speculos:latest
      ports:
        - 1234:1234
        - 9999:9999
        - 40000:40000
        - 41000:41000
        - 42000:42000
        - 43000:43000
      options: --entrypoint /bin/bash

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Download app binary
        uses: actions/download-artifact@v2
        with:
          name: monero-app-debug
          path: bin

      - name: Run test
        run: |
          nohup bash -c "python /speculos/speculos.py bin/app.elf --sdk 1.6 --seed \"abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about\" --apdu-port 9999 --button-port 42000 --automation-port 43000 --display headless" > speculos.log 2<&1 &
          pip install pytest
          pytest

      - name: Upload Speculos log
        uses: actions/upload-artifact@v2
        with:
          name: speculos-log
          path: speculos.log
